### ISSUE TITLE
Configuration not being applied for few audit policies

### ISSUE THREAD

**Issue by SwethaGanapathy01** [athaynes/xAuditPolicy#54] opened 2019-04-11 16:14 UTC
We have few DSC configurations which are not being applied to the server. Those are still in not configured state in server

- Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure'
- Ensure 'Audit Process Creation' is set to 'Success and Failure'
- Audit Other Object Access Events
- Audit MPSSVC Rule-Level Policy Change

Above recommendations are not applied eventhough we have configuration for all.
    
     AuditPolicySubcategory AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure
    {
        Name      = "MPSSVC Rule-Level Policy Change"
        AuditFlag = "Failure"
        Ensure    = "Present"
    }

    AuditPolicySubcategory AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess
    {
        Name      = "MPSSVC Rule-Level Policy Change"
        AuditFlag = "Success"
        Ensure    = "Present"
    }

**Comment by SwethaGanapathy01** [comment] 2019-04-15 12:16
Can anyone suggest me with some solution for the above issue with configurations

**Comment by joschirm** [comment] 2019-04-26 14:21
Hello @johlju and @athaynes , can some of you guys take a look at this?
I see that you both were engaged in another issue related to auditpolicyDSC.
Thanks,
Jonathan Schirmer

**Comment by athaynes** [comment] 2019-04-26 14:34
@joschirm @SwethaGanapathy01 Sorry for the delayed response. I have been out of the office. I'll take a look at this over the weekend and back to you in a couple of days.

**Comment by athaynes** [comment] 2019-04-26 14:53
I just ran a quick test to see if there were any errors, but I can't reproduce the issue described above. I copied the sample provided and here is the output from my windows 10 machine. I'll spin up a 2016 vm this weekend and run the same test. @SwethaGanapathy01 are you getting any errors when you run or apply the configuration?

```powershell
configuration testAuditPol
{
    Import-DscResource -ModuleName AuditPolicyDsc -ModuleVersion 1.4.0.0

    AuditPolicySubcategory AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure
    {
        Name      = "MPSSVC Rule-Level Policy Change"
        AuditFlag = "Failure"
        Ensure    = "Present"
    }
    AuditPolicySubcategory AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess
    {
        Name      = "MPSSVC Rule-Level Policy Change"
        AuditFlag = "Success"
        Ensure    = "Present"
    }
}
testAuditPol -outputpath C:\dev\auditpolicy


C:\WINDOWS\system32> auditpol /get /Subcategory:'MPSSVC Rule-Level Policy Change'
System audit policy
Category/Subcategory                      Setting
Policy Change
  MPSSVC Rule-Level Policy Change         No Auditing


C:\WINDOWS\system32> Start-DscConfiguration -Path C:\dev\auditpolicy -Wait -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer * with user sid *.
VERBOSE: [*]: LCM:  [ Start  Set      ]
VERBOSE: [*]: LCM:  [ Start  Resource ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]
VERBOSE: [*]: LCM:  [ Start  Test     ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]
VERBOSE: [*]:                            [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]
(GET) 'MPSSVC Rule-Level Policy Change':'Failure'
VERBOSE: [*]:                            [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]
'MPSSVC Rule-Level Policy Change':'Failure' is NOT 'Present'
VERBOSE: [*]: LCM:  [ End    Test     ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]  in
0.1660 seconds.
VERBOSE: [*]: LCM:  [ Start  Set      ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]
VERBOSE: [*]:                            [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]
(SET) 'MPSSVC Rule-Level Policy Change' audit 'Failure' to 'Present'
VERBOSE: [*]: LCM:  [ End    Set      ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]  in
0.0640 seconds.
VERBOSE: [*]: LCM:  [ End    Resource ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToFailure]
VERBOSE: [*]: LCM:  [ Start  Resource ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]
VERBOSE: [*]: LCM:  [ Start  Test     ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]
VERBOSE: [*]:                            [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]
(GET) 'MPSSVC Rule-Level Policy Change':'Success'
VERBOSE: [*]:                            [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]
'MPSSVC Rule-Level Policy Change':'Success' is NOT 'Present'
VERBOSE: [*]: LCM:  [ End    Test     ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]  in
0.0570 seconds.
VERBOSE: [*]: LCM:  [ Start  Set      ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]
VERBOSE: [*]:                            [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]
(SET) 'MPSSVC Rule-Level Policy Change' audit 'Success' to 'Present'
VERBOSE: [*]: LCM:  [ End    Set      ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]  in
0.0570 seconds.
VERBOSE: [*]: LCM:  [ End    Resource ]  [[AuditPolicySubcategory]AuditMPSSVCRuleLevelPolicyChangeIsSetToSuccess]
VERBOSE: [*]: LCM:  [ End    Set      ]
VERBOSE: [*]: LCM:  [ End    Set      ]    in  0.9610 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.21 seconds


C:\WINDOWS\system32> auditpol /get /Subcategory:'MPSSVC Rule-Level Policy Change'
System audit policy
Category/Subcategory                      Setting
Policy Change
  MPSSVC Rule-Level Policy Change         Success and Failure
```

**Comment by athaynes** [comment] 2019-04-28 05:43
@joschirm @SwethaGanapathy01 I ran the config on a 2016 VM in Azure (1607) and it works there as well. What version of 2016 are you running? What OS are you generating the MOF from?

**Comment by SwethaGanapathy01** [comment] 2019-04-30 09:53
Could you help me for how to check version of 2016 VM.

**Comment by gaelcolas** [comment] 2019-06-25 13:51
@SwethaGanapathy01 by running `gwmi win32_operatingSystem` for build number or `(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId` for release ID.

**Comment by gaelcolas** [comment] 2019-06-30 16:45
@SwethaGanapathy01 I'm closing this issue, but feel free to re-open with the provided info.

**Closed as completed by gaelcolas** 2019-06-30 16:45 UTC
